"""second

Revision ID: 61ad639be980
Revises: 19f07ef612ca
Create Date: 2021-03-02 00:53:42.622756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ad639be980'
down_revision = '19f07ef612ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('representative', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantuser_email'), 'restaurantuser', ['email'], unique=True)
    op.create_index(op.f('ix_restaurantuser_representative'), 'restaurantuser', ['representative'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_restaurantuser_representative'), table_name='restaurantuser')
    op.drop_index(op.f('ix_restaurantuser_email'), table_name='restaurantuser')
    op.drop_table('restaurantuser')
    # ### end Alembic commands ###
